# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b38e87c2e1773d326ec5b41c80282343b8e36d74fbbedcec0091e20be6111abcc09889502f6e6a810363d0ea91425771af6839bd6416a77db76f90411b66a3

test:
  secret_key_base: a4657f9b273e01fdc782902e8b31d7623c1b2cbb9f850805d3c7c56e771a4fc8f4f04207b0dfcaaf9af12f93080c6cd3fbc115490e96cb6ddb2314e6220df52e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
